# Generated by Django 5.2 on 2026-07-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_trial_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trial_started_at',
        ),
    ]
