# Generated by Django 5.2 on 2026-09-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
