# Generated by Django 5.2 on 2026-09-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_recovery_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
