# Generated by Django 5.2 on 2026-09-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('banner_severity', models.CharField(default='warning', max_length=20)),
                ('banner_text', models.TextField(default='Scheduled system maintenance in progress.')),
                ('default_trial_days', models.IntegerField(default=7)),
                ('auto_approve_owners', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('gateway_mode', models.CharField(default='sandbox', max_length=20)),
                ('feature_ai_menu', models.BooleanField(default=True)),
                ('feature_qr_ordering', models.BooleanField(default=True)),
                ('feature_whatsapp_alerts', models.BooleanField(default=False)),
                ('feature_analytics_export', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
