# Generated by Django 5.2 on 2026-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='estimated_completion',
            field=models.CharField(blank=True, default='Today at 3:00 AM UTC', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='lock_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='maintenance_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
