# Generated by Django 5.2 on 2026-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_systemsetting_estimated_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='free_tier_allow_kitchen_settings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='free_tier_allow_receipt_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='free_tier_allow_security_pin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='show_pro_badges_on_user_settings',
            field=models.BooleanField(default=True),
        ),
    ]
