# Generated by Django 5.2 on 2026-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_systemsetting_free_tier_allow_kitchen_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='hide_locked_settings_tabs',
            field=models.BooleanField(default=True),
        ),
    ]
