# Generated by Django 5.2 on 2026-09-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_systemsetting_hide_locked_settings_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='audit_log_retention_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='failed_login_lockout_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='free_tier_max_menu_items',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='free_tier_max_orders_per_month',
            field=models.IntegerField(default=50),
        ),
    ]
