# Generated by Django 5.2 on 2026-09-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='free_tier_max_tables',
            field=models.IntegerField(default=5),
        ),
    ]
