# Generated by Django 5.2 on 2026-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_systemsetting_free_tier_max_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='qr_engine_mode',
            field=models.CharField(choices=[('self_hosted', 'Self-Hosted (Local Media PNG/SVG)'), ('external_api', 'External API (api.qrserver.com)')], default='self_hosted', max_length=20),
        ),
    ]
