# Generated by Django 5.2 on 2026-07-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(choices=[('₹', 'INR (₹)'), ('$', 'USD ($)'), ('€', 'EUR (€)'), ('£', 'GBP (£)')], default='₹', max_length=10),
        ),
    ]
