# Generated by Django 5.2 on 2026-08-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_tracking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='restaurant_logos/'),
        ),
    ]
