# Generated by Django 5.2 on 2026-09-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_orderitem_options_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['section', 'table_number']},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='table',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='qr_code_svg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='section',
            field=models.CharField(blank=True, default='Main Area', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'section', 'table_number')},
        ),
    ]
