# Generated by Django 5.2 on 2026-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_payment_method_orderitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
