# Generated by Django 5.2 on 2026-09-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_cancellation_reason_order_is_recovered'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
    ]
