# Generated by Django 5.2 on 2026-09-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_restaurant_is_accepting_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
